  version: '2.3'

  services:
    config:
      build: config
      ports:
        - 8888:8888
      restart: always
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      logging:
        options:
          max-size: "10m"
          max-file: "10"

    discovery:
      build: discovery
      ports:
        - 8761:8761
      restart: always
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      logging:
        options:
          max-size: "10m"
          max-file: "10"
      depends_on:
        config:
          condition: service_healthy

    gateway:
      build: gateway
      ports:
        - 4000:4000
      restart: always
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      logging:
        options:
          max-size: "10m"
          max-file: "10"
      depends_on:
        config:
          condition: service_healthy
        discovery:
          condition: service_healthy
    test-service:
      build: test-service
      ports:
        - 8000:8000
      restart: always
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      logging:
        options:
          max-size: "10m"
          max-file: "10"
      depends_on:
        config:
          condition: service_healthy
        discovery:
          condition: service_healthy
        gateway:
          condition: service_healthy
    elasticsearch:
      image: elasticsearch:6.4.2
      ports:
        - 9200:9200
        - 9300:9300
    kibana:
      image: kibana:6.4.2
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
    logstash:
      image: logstash:6.4.1
      volumes:
        - ./logstash.conf:/tmp/logstash.conf
      command: logstash -f /tmp/logstash.conf
      depends_on:
        - elasticsearch

    zipkin:
      image: openzipkin/zipkin
      environment:
        - STORAGE_TYPE=mem
      ports:
        - 9411:9411

    keycloak:
      image: jboss/keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/cloud-realm.json
      ports:
        - 8080:8080
      volumes:
        - ./cloud-realm.json:/tmp/cloud-realm.json
